### ISSUE TITLE
BrianSharp & Activator#

### ISSUE THREAD

**Issue by nprotecc** [berbb/PortAIO-Loader#1]
-BrianSharp Yasuo not Load in game
-Yasuo Pro - Load but does not work
-Activator# - Failed to load
-ElutilitySuit- Failed to load.

again thanks for the great input.

**Comment by IlikeBaconLol** [comment]
Just try that : Fixed. Please reinstall the updater here : https://github.com/berbb/PortAIO-Updater/releases

And update your dlls.

**Comment by IlikeBaconLol** [comment]
Oh my bad its about the sdk.

**Comment by nprotecc** [comment]
It still does not load

**Comment by liwaxora** [comment]
Berb said yesterday that he will add the SDK.

**Comment by berbb** [comment]
BrianSharp is fixed. It will be in Patch 1.0.0.2.
