### ISSUE TITLE
ElKatarina - Eleasy

### ISSUE THREAD

**Issue by hayatobaei** [berbb/PortAIO-Loader#109]
http://prntscr.com/c8nvbw Elobuddy error? and i crashed Crashing every time by this error http://prntscr.com/c8nxd9 - disabled ezvade and sfx and seems to be fixed
- edit i think it was eleasy - katarina

**Comment by berbb** [comment]
Very unsure where this error came from, I just checked the code for ElEasy - Kat and there's nothing that leads to the console error.
