### ISSUE TITLE
Hard freezes

### ISSUE THREAD

**Issue by Fearboy1** [berbb/PortAIO-Loader#118]
sorry for bad ingrish ㅋㅋㅋㅋ
Is it my shitty and pathetic PC or ElUtilitySuite after few minutes (sometimes it takes less time) freezes lol as fuck (it means i MUST restart my client to play,) 
**#feelsbadman**
well, i have tried to disable it and it kinda works.
give me advice how to totally prevent it and what utility script is working right now without any errors/problems (that at least doesn't freeze client like stupid whore)
thanks in advance.

**Comment by yMeliodasNTD** [comment]
huhu3

**Comment by yMeliodasNTD** [comment]
active Champion ohly ou desactive all utilyts ( not humanizer ) ;-;
