### ISSUE TITLE
Skill shots wont cast bug

### ISSUE THREAD

**Issue by Slayer7412** [berbb/PortAIO-Loader#123]
Some skill shots wont shoot:
 Like: Sivir Q-Janna Q-Teemo R
 
When i press the key it brings me to base or to some strange position
 
but well....even if i have smartcast,or with out it it still does the same thing.

**Comment by berbb** [comment]
With which champion?

**Comment by Slayer7412** [comment]
like i said up

Sivir,Janna,Teemo so far

Sivir Q,JannaQ,TeemoR

**Comment by berbb** [comment]
Oh I thought you were just giving an example, no need to be aggressive.

**Comment by Slayer7412** [comment]
Panda teemo for teemo,OKTW for Janna and Sivir
