### ISSUE TITLE
Brian Leesin doesn't use W on wardjump / inSec

### ISSUE THREAD

**Issue by lightduy94** [berbb/PortAIO-Loader#131]
Brian Leesin doesn't use W on wardjump / inSec. Please fix it!

**Comment by lightduy94** [comment]
And please add an toggle key for "Dodge only dangerous" in EzEvade :D

**Comment by Lemonadez** [comment]
Press Space Bar - Dodge only dangerous. or no evade..

No Semi Manual E..Cuz u no he only port. Ask the creator of ElTrist from L# forum. then he will port it if he have time.

**Comment by lightduy94** [comment]
@Lemonadez He already added Semi Manual E in PortAIO v1 so i just make a suggestion if he willing to add it!
