### ISSUE TITLE
Ezreal

### ISSUE THREAD

**Issue by crankless** [berbb/PortAIO-Loader#144]
When I start game with ezreal , game is crashing. And pls add to PortAIOV2 new assembly. 
Example : Plexpered Ezreal(Common) , Valvrave Sharp ( SDK) ,SDK Exor AIO ( SDK ) , Challenger Series (SDK)

plexpered - ezreal
Valvrave - yasuo zed lee sin 
sdk exor aıo - most adc
challenger series - vayne
 and pls challenger series(sdk) and sdk exor aıo(sdk) work at the same time when play vayne . because they are very good. you will see when try

**Comment by berbb** [comment]
SDK addons is not going to be added any time soon. So no Valvrave, no ExorAIO, and no ChallengerSeries.

**Comment by crankless** [comment]
Plexpered ezreal ?


4 Eylül 2016 Pazar tarihinde, Berb <notifications@github.com> yazdı:

**Comment by berbb** [comment]
All added. ^^
