### ISSUE TITLE
taliyah assembly

### ISSUE THREAD

**Issue by reactionss** [berbb/PortAIO-Loader#147]
Can you add " Taliyah - The Stoneweaver  " for dual-port.

**Comment by berbb** [comment]
Already added for 1.0.0.5. Hit up discord to know changelogs/upcoming features/announcements.

**Comment by reactionss** [comment]
how can i download 1.0.0.5 ? my elobuddy shows 1.0.0.0.

**Comment by berbb** [comment]
The PortAIO Loader will always be 1.0.0.0, the DLLS will be a different version.

**Comment by Lemonadez** [comment]
@berbb Actually 1.0.0.5 is already out on your own computer :) hehehe joke
