### ISSUE TITLE
Vayne hunter reborn antigapcloser not working & the evade's need a rework/ a look at 

### ISSUE THREAD

**Issue by BigPhalus** [berbb/PortAIO-Loader#149]
Title ^^ as for the evade's, in ezevade most straight linear spells stop being considered before they reach their end point meaning that at first it will start to evade for the first 0.5 s but then stops evading and gets hit (good example is caitlyn Q in my case). 
In evade# problem once more comes from linear spells, however only some of them, in the case of evade# it creates the projectile too late so evades too late, about a whole second later (once more a good example is caitlyn Q).
To see the problem more clearly make sure drawing is on.

**Comment by One2Triple** [comment]
Is it even loading for you? For me it crashes in every game, had to use a different script set :/

**Comment by BigPhalus** [comment]
I have had no problems with vayne hunter reborn yet, no crashes nothing and have been using it for quite some time, think your problem comes from something else your loading (maybe another utility or something)
