### ISSUE TITLE
(Suggestion/Request) hi im gosu

### ISSUE THREAD

**Issue by ZangiefWins** [berbb/PortAIO-Loader#150]
Hi! Long time no see.
So, first of all, I'd like to say thanks.
I'm really enjoying the second version of PortAIO. It really has everything, except for one thing that I miss so much: my favorite Vayne script.
I think hi im gosu is such a simple but pretty much the best Vayne script I've used in a while, and it was in the first version, so it might not be that hard to port (not sure about that though, since I don't know shit about script porting). Thus, I'd like to suggest/request this port.

That's it, have a good day and thanks again!

**Comment by BigPhalus** [comment]
Doctor Berb MD - 08/28/2016
[Patch 1.0.0.5 - NOT RELEASED]
-------------------------------------------------------------------------------
[ADDED DUAL-PORT] - Added a Lux that can't be named
[ADDED DUAL-PORT] - Added a Draven that can't be named
[ADDED DUAL-PORT] - Added hi im gosu (Vayne)


in other words it will be available in the next update, you can find the changelogs on the discord server ^^

**Comment by berbb** [comment]
^^
