### ISSUE TITLE
Turn off Disable drawing in PortAIO on Streaming Mode?

### ISSUE THREAD

**Issue by FoxyKunDesu** [berbb/PortAIO-Loader#153]
Hey there! I personally use the streaming mode as a Buddy so I can record videos for fun, but when I try to use portAIO-loader I can potentially open up the menu on accident because PortAIO's disable drawing allows the menu to stay active when pressing shift. This may be due to how L#'s menu works, but I cannot be for certain. The easy way to disable this is to change the menu key from shift to another key, but there is currently no option to change hotkeys. If possible, can you add something to either combat the menu activation on disable drawings or allow the menu key to be changed at will?

**Comment by berbb** [comment]
Unfortunately, L#'s streaming mode does work this way. And I'll be adding a menu function to change the L# Menu button.
