### ISSUE TITLE
ARAMDetFull Crash

### ISSUE THREAD

**Issue by TheKushStyle** [berbb/PortAIO-Loader#16]
http://pastebin.com/fJ4Tq237

**Comment by berbb** [comment]
Damn, this is caused by EloBuddy's Sandbox, it's not letting us access the LoL's Database to get items. I'll experiment with this and see what I can do.

**Comment by haxorwannabe** [comment]
I think autojungler have the same problem

**Comment by berbb** [comment]
Fixed most of DETFull's issues, will appear in another update though.
