### ISSUE TITLE
right click crash

### ISSUE THREAD

**Issue by AwesomeIsMatt** [berbb/PortAIO-Loader#161]
portAIO still crashing.. Whenever i enter game, it allows me to buy items, but when i right click to move, client stops responding, Happen 3/3 in PVP and 5/5 in AI.. Tried different champs - It even allows me to press enter to talk, just right clicking to move, crashes the LoL Client
And its only with PortAIO, EloBuddy works when I close portaio and use one of their addons.

Server - NA

Same outcome with every LOL mode.

**Comment by lightduy94** [comment]
Disabled "Streaming mode" in EB Loader. It's bugging

**Comment by Lemonadez** [comment]
Stop getting money from streaming while hacking!
