### ISSUE TITLE
Aram autoplay not leveling correctly

### ISSUE THREAD

**Issue by Nitroxko** [berbb/PortAIO-Loader#165]
Regardless of the champ it starts leveling 2 in w and 1 in e, and it doesn't level ultimate at all

**Comment by Nitroxko** [comment]
> #103

**Comment by berbb** [comment]
Fixed in 1.0.0.6

**Comment by Nitroxko** [comment]
Re-Opened, problem still isn't fixed

**Comment by berbb** [comment]
because we're not at 1.0.0.6....
