### ISSUE TITLE
How to update to 1.05?

### ISSUE THREAD

**Issue by doenutts** [berbb/PortAIO-Loader#169]
When i load in it says i have 1.04 to run aio updater, I have run aio updater but it still shows I have 1.04? I have tried download manual on aio updater as well. I am using the latest aio updater. What am i doing wrong

**Comment by doenutts** [comment]
How do I make my settings on the leaguesharp menu stay, like in oktw and stuff it erases everytime i load up. thanks dude

**Comment by berbb** [comment]
Try running it as admin

**Comment by doenutts** [comment]
Yeah I have tried that, I've even tried copying your updated files and
putting them in the respective places to no avail. still loads up as 1.04

**Comment by doenutts** [comment]
is tehrte any other solution please?

**Comment by berbb** [comment]
Download the two DLLs on the github page, and put them in %appdata%\EloBuddy\Addons\Libraries
