### ISSUE TITLE
game freeze when clicking in game menu 

### ISSUE THREAD

**Issue by jarviskao** [berbb/PortAIO-Loader#174]
I use portAIO in garena but it seem that it is not compatible with. Game is freezing when i click the in-game (L#) menu. I have reinstall elobuddy and cleaned the data from %appdata% but it still doesn't work. However,addons of elobuddy work normally. How can i to fix it?

**Comment by Muse30** [comment]
can you show the ingame console? I had this error too

**Comment by jarviskao** [comment]
@Muse30 
PortAIO is Loaded at begining. It work fine for a while (around 5 mins) if i don't touch/modify the content of the (L#) menu. Game freeze whenever i press the menu.

**Comment by jarviskao** [comment]
I can't use PortAIOv2. However, using the old PortAIO not v2 , it work normally. @berbb
