### ISSUE TITLE
Now working

### ISSUE THREAD

**Issue by ale3x21** [berbb/PortAIO-Loader#175]
Not working anymore for me.

**Comment by Muse30** [comment]
??? it is working

**Comment by ale3x21** [comment]
It's not loading the right champ script

**Comment by Fearboy1** [comment]
its because of ivern update, all champs ID have been moved to +1.

**Comment by Muse30** [comment]
yes I saw that mb

**Comment by ale3x21** [comment]
Any update soon?

**Comment by berbb** [comment]
It's working fine with the 1.0.0.51 update
