### ISSUE TITLE
Limit game PORTAIO

### ISSUE THREAD

**Issue by brianzk** [berbb/PortAIO-Loader#188]
Bro, 
I play two games & not inject at the moment.

**Comment by Muse30** [comment]
it will be fixed tomorrow

**Comment by ale3x21** [comment]
Fixed?

**Comment by Muse30** [comment]
https://github.com/berbb/PortAIO-Loader/wiki/Installation-Guide

**Comment by brianzk** [comment]
Nice work, ty berb & Muse!!
