### ISSUE TITLE
OKTW AND SEBBY BAN WARS 

### ISSUE THREAD

**Issue by yMeliodasNTD** [berbb/PortAIO-Loader#21]
hey berb oktw crashing game sometimes when using the button of the lane clear ;/ (no erro in console),Sebby ban wars blocking ALL manual E whith vayne and Q whit sivir

**Comment by berbb** [comment]
Sebby Ban Wars has that issue, it's not a bug. The original blocks spells also. I'll look into the lane clear error.

**Comment by yMeliodasNTD** [comment]
it literally blocks all E manual or script

**Comment by berbb** [comment]
Lane Clear shouldn't crash at all anymore, I can't guarantee it but I've added a lot of checks to make sure it doesn't do anything it shouldn't.

Fixed in 1.0.0.3.
