### ISSUE TITLE
Crash report.

### ISSUE THREAD

**Issue by portes420** [berbb/PortAIO-Loader#24]
![8c5a52fc2626ba2a9fc7df8d836a2838](https://cloud.githubusercontent.com/assets/13965996/17607715/e49de296-5ffd-11e6-8f64-3e1b8f7cf53f.png)
Played Gp Underrated AIO. 

> [https://gyazo.com/8c5a52fc2626ba2a9fc7df8d836a2838](url)

**Comment by berbb** [comment]
Will be fixed in 1.0.0.4
