### ISSUE TITLE
Closed Source?

### ISSUE THREAD

**Issue by pellep12** [berbb/PortAIO-Loader#27]
Will PortAIO v2 only be closed source?
(Precompiled dll files only?)

**Comment by berbb** [comment]
Yes

**Comment by chjmkbiet** [comment]
![image](https://cloud.githubusercontent.com/assets/20781835/17610223/08a0f1ca-6066-11e6-93a2-76ad35e3752b.png)
I installed addon download your copy is not

**Comment by pellep12** [comment]
Oh :(
Guess ill fork the old PortAIO v1 repo and stick to that for now.

Thanks for the fast answer tho :)
