### ISSUE TITLE
Yasuo - Addon * Vr 1.0.0.2 (Error-Load)

### ISSUE THREAD

**Issue by nprotecc** [berbb/PortAIO-Loader#28]
After the update does not load any yasuo addon

**Comment by nprotecc** [comment]
When you upload utilities, do not charge the addon of yasuo.

and if loads yasuo addon not load utilities.

**Comment by berbb** [comment]
[![](http://image.prntscr.com/image/e5a120eb44b6493dba6cd4270cd69a4f.png)]()
[![](http://image.prntscr.com/image/b04ebd3acde74fb49f325db9bf340bb1.png)]()
[![](http://image.prntscr.com/image/aff8ea2c75a647bc8ce8b41150f7683e.png)]()

Seems to work fine.
