### ISSUE TITLE
VayneHunterReborn

### ISSUE THREAD

**Issue by bingbongbing** [berbb/PortAIO-Loader#3]
1. Not loading.
2. Selecting VayneHunterReborn causes no utilities to load (utilities load with OKTW/hiki/iSeries/etc).

**Comment by bingbongbing** [comment]
https://gyazo.com/3964b1fa110afbc5da5e573b2c58e0d0

**Comment by berbb** [comment]
Fixed. Please reinstall the updater here : https://github.com/berbb/PortAIO-Updater/releases

And update your dlls.
