### ISSUE TITLE
Utility Bugs

### ISSUE THREAD

**Issue by BEEBEEISADOG** [berbb/PortAIO-Loader#30]
![problem](https://cloud.githubusercontent.com/assets/6389032/17609733/497df8ba-606a-11e6-8bfa-eb8387ba67f4.PNG)
![problems](https://cloud.githubusercontent.com/assets/6389032/17609734/49802838-606a-11e6-8755-2ca084fce7ff.PNG)

**Comment by berbb** [comment]
Will be fixed in 1.0.0.4
