### ISSUE TITLE
 Menü Issu/Question

### ISSUE THREAD

**Issue by happymaj00r** [berbb/PortAIO-Loader#31]
Cant install Failed but other addon´s work 

Build Log: http://pastebin.com/1pKLg2Cg

and yeah i have installed the updater 
an i reinstalled the dll´s like 3 times

this happend after i delet %appdata%/Elobuddy 

WORK NOW IDK WHY but see antoher question 

--------------------------------------------------
another question if i press shift the new L# Menu and the Elobuddy menu open is there a 
opportunity to turn the EB menü off ?

**Comment by berbb** [comment]
No you can't turn off the EB menu. In later patches I'll make an option to change the menu key.
