### ISSUE TITLE
Riven not AA in between Q

### ISSUE THREAD

**Issue by leagueboy123** [berbb/PortAIO-Loader#33]
None of the riven assemblies seem to work properly, Hoola Riven was working perfectly last night when V2 just got released but today it's been very buggy. It just spams Q when you go for combo, and even by itself it just spams Q. I tried the other assemblies and none use AA in between Q.

**Comment by rajuritik** [comment]
same

**Comment by berbb** [comment]
Will be fixed in 1.0.0.4
