### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by Pedrinh0w** [berbb/PortAIO-Loader#34]
![image](https://cloud.githubusercontent.com/assets/20982928/17612491/c37a7e6e-6028-11e6-9b97-2cdd4c09831a.png)

i got this error then crash, more then 100 times in a game, other times with baron bug name was "SuperRecall is not supported yet. Please Report It"

**Comment by berbb** [comment]
Crashes are hard to fix, we don't know where it's coming from. As for the error code it'll be fixed in 1.0.0.4
