### ISSUE TITLE
Nechrito Nidalee bug

### ISSUE THREAD

**Issue by GlitchLeague** [berbb/PortAIO-Loader#36]
At the beginning of the game Nechrito Nidalee doesn't throw any skillshots. After a few minutes it starts throwing skillshots and the errors shown below disappear.

![3nhdte1](https://cloud.githubusercontent.com/assets/20990101/17621672/3c2a0340-6095-11e6-90fd-38ed562eb0e5.png)

And whenever I am on the red side, my game crashes whenever I open up my shop

![vi8w43p](https://cloud.githubusercontent.com/assets/20990101/17621715/9380901e-6095-11e6-9680-743b34b2eb53.png)

**Thanks for making PortAIO v2 btw!**

**Comment by berbb** [comment]
Will be fixed in 1.0.0.4
