### ISSUE TITLE
PortAIO v2 loads Lulu instead of Lucian

### ISSUE THREAD

**Issue by PUR3-Mannerheim** [berbb/PortAIO-Loader#38]
I went into a normal game as Lucian and PortAIO loaded Lulu addons instead of Lucian's for some reason.

**Comment by berbb** [comment]
This was fixed in 1.0.0.2. Either your libs are outdated (run the PortAIO-Updater to update them) or your EB is outdated. You mostly likely need to run PortAIO-Updater.
