### ISSUE TITLE
issues

### ISSUE THREAD

**Issue by Sharpino** [berbb/PortAIO-Loader#4]
-elsejuani auto and semi ult not working + q is very slow
-underrated sejuani not loading: https://s9.postimg.org/pank9ghbj/Screenshot_3.png

-elutility:
smite ks not working
smite not wokring on dragons
https://s10.postimg.org/lwami9nbt/Screenshot_4.png
recall tracker not 100% working?

**Comment by IlikeBaconLol** [comment]
About underrated sejuani not loading : Fixed. Please reinstall the updater here : https://github.com/berbb/PortAIO-Updater/releases

And update your dlls.

It should fix most of your issues, recall teacker is maybe a packet issue.

**Comment by nprotecc** [comment]
Preojec Fiora- colapse obwalker
Fiora Addon; xScalice need Update Messg-not load
Fiora: UnderratoIO_ Not load

**Comment by berbb** [comment]
Everything but recall tracker will be fixed/updated in Patch 1.0.0.1.
