### ISSUE TITLE
PortAIL two series?

### ISSUE THREAD

**Issue by 2399604364** [berbb/PortAIO-Loader#47]
PortAIL-Updater and PortAIL-Loader and what is what is the same?I do not understand some.

**Comment by 2399604364** [comment]
I installed ELOBUDDY PortIO-Updater, it can not be injected into the game, choose PortAIO-Loader can be used, how else?

**Comment by BigPhalus** [comment]
on the portaio-updater github page click on "releases" tab on the top right and download the .exe

**Comment by berbb** [comment]
PortAIO-Updater.Exe Installation Instructions :
1. Download the lastest release of the PortAIO-Updater.exe : https://github.com/berbb/PortAIO-Updater/releases

2. Open PortAIO-Updater.exe as administrator.

3. Click on the download/update button to download the latest dlls or update them if you already have them.

4. Once the status says "PortAIO installed. (Up to date)" you are ready to download the loader that will run PortAIO. (http://image.prntscr.com/image/5e72300b5e024b61a0a32eb691b7f069.png)

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

PortAIO-Loader Installation Instructions :
1. Once all your dlls are updated head to the EB launcher and click the green install addon button. (http://image.prntscr.com/image/a52341b82a4d4853b787089d5faa664d.png)

2. Once the "Addon Installer" box is open copy and paste https://github.com/berbb/PortAIO-Loader into the box where it says "Remote Addon". 
(http://image.prntscr.com/image/4cedac617c8a4e4c9b171c0f3c93bef5.png)

3. Click install and wait for it to pop up a box like : http://image.prntscr.com/image/86bade09bf1546f49d14799e76d988c2.png

4. Check the PortAIO-Loader install checkbox and hit the blue install button.

5. Once you have clicked it give it a few seconds for it to download & install.

6. The box will close on its own and you will get this addition to your loader : http://image.prntscr.com/image/0885c6e0faca47a09b82eab3494654d8.png

If for some reason your PortAIO-Loader status says compiling error re-do everything in the PortAIO-Update.Exe instructions.
