### ISSUE TITLE
Garen

### ISSUE THREAD

**Issue by Lemonadez** [berbb/PortAIO-Loader#49]
I am Not using any Utility just Champion mode only to see why it crash.

I tried different settings, turning off entire settings on Garen settings. Everytime I press Space, It just freeze my client and crash. No Error console.

Is there OKTW Garen?

**Comment by berbb** [comment]
There is not a OKTW Garen but if whenever you hit combo it crashes it is most certainly a PortAIO issue, I'll check it out.

**Comment by berbb** [comment]
Will be fixed in 1.0.0.4
