### ISSUE TITLE
PortAIO-Loader Crash{but PortAIO(First version) working}

### ISSUE THREAD

**Issue by Justifiied** [berbb/PortAIO-Loader#51]
Many Champs crash with portAIO-Loader,like Slutty Ryze..But when i use PortAIO(The First version) it's working...I hope i will help you to fix it..I like your job man

**Comment by berbb** [comment]
Most of the crashes were related to EB at the time of this issue but some crashes related to PortAIO will be fixed in 1.0.0.4
