### ISSUE TITLE
L# vs PortAIO - the differences, the bugs etc.

### ISSUE THREAD

**Issue by hiimhaxy** [berbb/PortAIO-Loader#56]
Okay folks, so I decided to make a little comparison. I played two games with Jinx - one with L#, one with PortAIO 2.0. I played with OKTW Champion mode only in both cases (with OKTW pred), ElUtilitySuite with disabled cleanse/heal and EzEvade, as well as Sebby Ban War with 175 delay.

What I can say is that currently, PortAIO feels like 70-75% of native L# experience. Compared to original OKTW, the champion script works rather fine, but ported pred feels a little bit off. Sometimes it misses W/R terribly D:. Orbwalker can be also problematic sometimes as it tends to miss lasthits (https://github.com/berbb/PortAIO-Loader/issues/54 and it also sometimes stops to move when pressing Mixed/Lane clear (http://prntscr.com/c5w6ad). Going further, EzEvade worked fine, just as if it was played on L#. ElUtility is ok but we need to wait for finndev to fix EB Core so it doesn't crash anymore. However, I noticed some visual bugs - notification cards are messed up a little (http://prntscr.com/c5w7gp), cd tracker is a bit off position (http://prntscr.com/c5w7cx). Overall, I think if Berb will work on this more we can get better, more fluid experience. Maybe one day SDK scripts will arrive as well when SDKEx gets fixed.

**Comment by BigPhalus** [comment]
I would suggest to change the pred to SDK, I tried out all of them and SDK seems to be the one working the best so far, in my experience OKTW pred seems to wait way too long for just a mediocre shot (In the ported version that is)

**Comment by berbb** [comment]
Most of these issues are fixed in 1.0.0.4.
