### ISSUE TITLE
My fix to the crashes 

### ISSUE THREAD

**Issue by BigPhalus** [berbb/PortAIO-Loader#57]
following my compilation of crashes in #46 I have come to a temporary fix that I have tested 3 times and seems to work for me(tested with Ezevade ,vaynehunterreborn, Activator#). 

--> make sure you have NO elobuddy addons loaded. 
--> go in elobuddys target selector place all champions as priority 5.
--> make sure all elobuddy orbwalker hotkeys are on a key you will not use.
--> in elobuddys menu under core make sure ticks per second is on 1.
--> untick all options in elobuddys orbwalker (example fast kiting, attack other objects).
--> under orbwalker/advanced make sure "use game.on.tick" is the selected option.
--> under orbwalker/advanced make sure "disable orbwalking" and"disable moving to mouse" is ticked 
--> disable all drawings coming from elobuddy including elobuddys orbwalker drawings.
--> disable elobuddy's anti-gapcloser (do this by making sure non of the gapclosers are ticked)

Recommendations:
-->strongly advise to turn off trackers
-->inject once you are actually in game (away from fountain) rather than during loading screen [not too important]
--> If you want to use OKTW scripts make sure you disable the intro image in custom before starting a real game (found in OKTW menu>about>intro image) [even then I still recommend to avoid OKTW]

And that is it, the general idea is to reduce elobuddys interaction with the game to a minimum as I believe the crashes come from elobuddy and not portaio (or the combination of both). 
Please note: following this I do have a crash or 2 at the beginning of the game (before minions come) and also I haven't tested this with all addons so no guarantee's (kappa). 
Have fun.

**Comment by berbb** [comment]
Very nice list and analysis,, I'll reference this in the discord so the users can try this solution.

**Comment by Lemonadez** [comment]
Turn off the Stuff in OKTW Loading message. OKTW doesnt crash for me.

**Comment by serseriler22** [comment]
I have tested 4 times and  seems to work thanks !

**Comment by kuant** [comment]
All scripts that uses ignite  crashes
