### ISSUE TITLE
Vayne Hunter Reborn

### ISSUE THREAD

**Issue by westisnorth** [berbb/PortAIO-Loader#63]
VHR dont use e  stun anyone

**Comment by berbb** [comment]
Are you using SebbyBanWars?

**Comment by westisnorth** [comment]
i was using but i disabled it but still same

**Comment by westisnorth** [comment]
and ezevade sometimes cant escape from skilshots

**Comment by BigPhalus** [comment]
Ive been using vhr for some quite some time now and its been working fine for me, mess around with the settings in the assembly, as for ezevade yes there is a problem, it stops drawing/evading the skillshot early before it actually has the missle has evaporated.

**Comment by berbb** [comment]
Tested and it's using it. Sebby Ban Wars is the prime cause for skills not casting.
