### ISSUE TITLE
Evade, ezevade question 

### ISSUE THREAD

**Issue by serseriler22** [berbb/PortAIO-Loader#69]
I wanna use both can we do that. It is better in my opinion http://hizliresim.com/jBL5QG

**Comment by BigPhalus** [comment]
Problem with this is, their pathfinding are different (although similar) so theres a possibilty once a skillshot comes your way evade# will spam commands for you to go one way whilst ezevade will spam commands to go another way.... in the end your champ wont go anywhere and you will look for very robotic.
Having said that there is an option to avoid this, if you tick "click only once" in ezevade it should avoid this but it still pretty much pointless to have both enabled, but do what u want.

**Comment by berbb** [comment]
I'm not sure if I'm going to do something like this any time soon but I'll see if I can make a standalone or something.
