### ISSUE TITLE
Freeze

### ISSUE THREAD

**Issue by Ventis10** [berbb/PortAIO-Loader#7]
When I play, for example, Vayne after pressing the shift key game freezes

**Comment by berbb** [comment]
I can't image this is constantly happening. What is the average FPS you play on?

**Comment by Ventis10** [comment]
I play all the time in over 200 fps
When i do not depress the shift script works fine, but when I start to play with the settings all breaks down: /

**Comment by Ventis10** [comment]
![image](https://cloud.githubusercontent.com/assets/20966910/17598111/4222668a-5ff9-11e6-8b26-69586fb7827b.png)


Totally game falls

**Comment by Soofire** [comment]
I have the same problem

**Comment by nprotecc** [comment]
apparently is a problem of elobuddy...

**Comment by Soofire** [comment]
After reinstalling eb - still the same

**Comment by Ventis10** [comment]
Nothing helps

**Comment by berbb** [comment]
This is a very weird issue, I would think it was FPS drops or something but it clearly isn't. I also run at an average of 200 FPS. I tried to recreate that issue with Veigar and stuff but I just couldn't. 

Try reinstalling DirectX. https://www.microsoft.com/en-us/download/details.aspx?id=8109

**Comment by Soofire** [comment]
I reinstall DirectX but still have this problem. I can't do anything in menu.

**Comment by Soofire** [comment]
http://screencast.com/t/2V1P0PqBEVwP

**Comment by Lemonadez** [comment]
That your Operating System problem.. We are not having the same problem as you do.. I also tried it on Windows 7 VMWARE. Still not getting same result as you do.

The best thing is reformat your computer and install all the requirements for Elobuddy. Make sure you are on Bordlerless. Not Window Mode.

**Comment by Soofire** [comment]
Ahh so I can't do anything without reformat system ?

**Comment by Soofire** [comment]
After reformat system have the same problem .... WTF

**Comment by Ventis10** [comment]
yeach... new patch and all time this same problem i cant change script settings cuz crash and crash and crashhh :(

**Comment by berbb** [comment]
This is definitely not a PortAIO problem anymore. This is a hardware issue most likely in graphics.
