### ISSUE TITLE
Gangplank Crash

### ISSUE THREAD

**Issue by exorcistqq** [berbb/PortAIO-Loader#72]
crashed on pressing harrass button after like 2-3 q .

**Comment by westisnorth** [comment]
Which addon?  If you write berb can fix

**Comment by Wa1L** [comment]
Underrated AIO i believe , had crashes too with it early on

**Comment by berbb** [comment]
It's because of the Orbwalker that most UnderratedAIO champions are crashing, it'll be fixed in 1.0.0.4
