### ISSUE TITLE
Portaio Loader Failed 

### ISSUE THREAD

**Issue by Burbb** [berbb/PortAIO-Loader#73]
Already downloaded the most recent version of PortAIO Updater, but when i try to install the loader in Eb , says "failed".

**Comment by berbb** [comment]
Did you check %appdata%\EloBuddy\Addons\Libraries to see if PortAIO.dll and PortAIO.Common.dll was there?

And do you have 4.6 Framework for .Net? : https://www.microsoft.com/en-us/download/details.aspx?id=48130
