### ISSUE TITLE
ReformedAio - DIANA

### ISSUE THREAD

**Issue by LindsNemesis** [berbb/PortAIO-Loader#74]
ReformedAIO - Diana dont is making nothing just walk and dont make combo or harass 
If you can in the future can you port Moon Diana <3

**Comment by berbb** [comment]
I'm not taking requests but I'll check the ReformedAIO issue.

**Comment by LindsNemesis** [comment]
Ok, Thanks

**Comment by berbb** [comment]
Fixed and will be pushed in 1.0.0.4
