### ISSUE TITLE
Riven Script

### ISSUE THREAD

**Issue by TheExiledAE** [berbb/PortAIO-Loader#75]
Can you add Nechrito riven? Cause the hoola riven is outdated and it makes me crash.Thanks in advance, nechrito riven is the best :^)

**Comment by berbb** [comment]
Not talking requests.

**Comment by TheExiledAE** [comment]
You just told it in the portaio.ml.. Don't buy ported addons, ask via an
issue and we'll do it for free.

**Comment by TheExiledAE** [comment]
Thanks, I prefer you to remove Kurisu Riven because it doesnt use q in minions and its buggy, nechrito is always updated tho.Thanks again,I will wait for PortAIO to be more stable! Good Job and God bless
