### ISSUE TITLE
Berb.Common

### ISSUE THREAD

**Issue by brandon88man** [berbb/PortAIO-Loader#81]
Is berb.common needed to run portaio v2 ?

**Comment by edubuenoz** [comment]
No u need The UpdaterPortAIO-Updater.Exe Installation Instructions :
1. Download the lastest release of the PortAIO-Updater.exe : https://github.com/berbb/PortAIO-Updater/releases

2. Open PortAIO-Updater.exe as administrator.

3. Click on the download/update button to download the latest dlls or update them if you already have them.

4. Once the status says "PortAIO installed. (Up to date)" you are ready to download the loader that will run PortAIO. (http://image.prntscr.com/image/5e72300b5e024b61a0a32eb691b7f069.png)

**Comment by berbb** [comment]
^^^
