### ISSUE TITLE
not an issue but a suggestion

### ISSUE THREAD

**Issue by Wa1L** [berbb/PortAIO-Loader#85]
since its closed source now , can we get the changelog after each update or something like that .. would be cool though

**Comment by BigPhalus** [comment]
this is a good suggestion,  meanwhile not sure if you know about this but you can see if any changes were made to the closed source via this page: https://github.com/berbb , look at the squares an whatever commit was done in a private repository, most of the these commits are done to the closed source of portaio (:

**Comment by fluut** [comment]
it's on discord

**Comment by Sharpino** [comment]
https://discordapp.com/channels/177241543600635904/213010335433621504

**Comment by berbb** [comment]
I would take this suggestion but I won't because something bigger is coming up ;) that will take this suggestion accept it there.
