### ISSUE TITLE
SAC riven crashing

### ISSUE THREAD

**Issue by evyataRars** [berbb/PortAIO-Loader#87]
Synx auto carry riven is crashing while pressing the burst key, its just e>ult and crashing.
only portaio was loaded w/o ultilites.

hope i helped, thanks for all of ur hard work :D

**Comment by TheExiledAE** [comment]
Uhm... Hi have you tried doing this fix? https://github.com/berbb/PortAIO-Loader/issues/57, If not you should try because I'm using SAC Riven and it doesn't crash.

**Comment by evyataRars** [comment]
just tried it, still crashing, + its crashing randomaly when im farming manually

**Comment by TheExiledAE** [comment]
Well I think you should try kurisu riven? I use kurisu for the laning clear and the burst.Btw if pressing v doesn't q and aa on minion try checking the orbwalker and setting it to the original orbwalker keys.
