### ISSUE TITLE
Game Crush

### ISSUE THREAD

**Issue by bestoneuwest** [berbb/PortAIO-Loader#9]
##Played Kortatu Xerath with all the utilitys (ezevade,sfx...). I got game crush when i try go attack Oriana Bot under his turret, reconect, go mid lane and got crush again under the tower. Then i switch to old portAIO and played only utility with Hellsing Xerath, and got crush again under nexus tower when i try to kill blitz.
Maybe this is EB problem, bcs i got crush with the old port 2, but idk...

**Comment by bestoneuwest** [comment]
Game 2, playing kogmaw with OKTW and same utilitys, game crush in my base. Swithc to old port with utility and exor kogmaw and its ok

**Comment by bestoneuwest** [comment]
Game 3, Hellsing Xerath with old port utility, game crush one time at 16 min.

Hope this helps for faster fix :P

**Comment by Haxory** [comment]
Utilities are mostly the reason for crashing

**Comment by liwaxora** [comment]
Same issue but i think it"s due to the champ addons too i played with riven and fiora (full crash)
then i played with Zed (no crash) i don"t know it's just a supposition.

**Comment by kuant** [comment]
Jinx crash also
