### ISSUE TITLE
the new port aio update have some problems with autobuddytreeline

### ISSUE THREAD

**Issue by coreAIM** [berbb/PortAIO-Loader#94]
hay since the last portaio update today portaio have some problems with autobuddytreeline
autobuddytreeline is simply doing nothing if portaio is enabled
before the update it was working perfectly fine with autobuddytreeline .

**Comment by berbb** [comment]
I can't do anything about that lol. That's not even a port in PortAIO.

**Comment by coreAIM** [comment]
well i asked tyller and he told me that he did no changes to autobuddytreeline and i should contact u , since there have to be a reason why portaio is breaking autobuddy since the last update ^^

**Comment by berbb** [comment]
No. We don't support those add-ons so we can't do anything.
